### PR TITLE
init api and fetch data

### PR DESCRIPTION
**Pull request by developer-digital**
init api to get list video from youtube api
https://edu-redmine.framgia.vn/issues/6676

### CODE REVIEW

**Comment by developer-digital** [comment]
ready

**Comment by tuanlvt-1117** [comment]
Tách Pull ra e

**Comment by tuanlvt-1117** [comment]
commented

**Comment by developer-digital** [comment]
ready

**Review by tuanlvt-1117 — APPROVED** [review]

**Pull request merged**
